# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

  # reusable
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repo Name
      run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Get Current Action URL
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
      run: |
        echo "Current Action URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo "CURRENT_ACTION_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV

    - name: Parse PR Description for Dependencies
      id: parse-dependencies
      run: |
        set -x
        # 获取当前 PR 的描述
        cat > pull_request.body.txt <<'EOF'
        ${{ github.event.pull_request.body }}
        EOF
        DEPENDS_ON=$(grep -oP 'depends-on:\s*\[[^]]+\]' pull_request.body.txt | sed 's/^ *//;s/ *$//')
        echo "PR DEPENDS_ON: $DEPENDS_ON"
        DEPENDS_ON=$(echo "$DEPENDS_ON" | grep -oP '(?<=\[)[^]]+(?=\])') || true
        DEPENDS_ON=$(echo $DEPENDS_ON | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        DEPENDS_ON=$(echo "$DEPENDS_ON" | awk '{for(i=1;i<=NF;i++) if(!a[$i]++) printf "%s%s",$i,(i==NF?ORS:OFS)}')
        ALL_PR="$DEPENDS_ON ${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
        ALL_PR=$(echo $ALL_PR | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        ALL_PR=$(echo "$ALL_PR" | awk '{for(i=1;i<=NF;i++) if(!a[$i]++) printf "%s%s",$i,(i==NF?ORS:OFS)}')
        manifest_part=$(echo "$ALL_PR" | grep -o 'open-vela/manifests[^ ]*') || true
        if [ "$manifest_part"X != ""X ]; then
          without_manifest_pr=$(echo "$ALL_PR" | sed "s|$manifest_part||" | xargs)
          ALL_PR="$manifest_part $without_manifest_pr"
        fi
        echo "ALL_PR=$ALL_PR" >> $GITHUB_ENV
        echo "DEPENDS_ON=$DEPENDS_ON" >> $GITHUB_ENV
    
        for DEPENDENCY in $DEPENDS_ON; do
          REPO_NAME=$(echo $DEPENDENCY | awk -F'/pull/' '{print $1}')
          PR_NUMBER=$(echo $DEPENDENCY | awk -F'/pull/' '{print $2}')
          PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.CI_PAT_ROBOT }}" "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER")
          LATEST_SHA=$(echo "$PR_COMMITS" | jq -r '.head.sha')
          if [[ -z "$LATEST_SHA" ]]; then
            echo "No commits found for PR #$PR_NUMBER or invalid API response."
            exit 1
          fi
          curl -X POST \
            -H "Authorization: token ${{ secrets.CI_PAT_ROBOT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_NAME/statuses/$LATEST_SHA \
            -d '{
              "state": "pending",
              "description": "In progress",
              "context": "CI triggered by other PR",
              "target_url": "${{ env.CURRENT_ACTION_URL }}"
            }'
          COMMENT_BODY="CI started by ${{ github.repository }}/pull/${{ github.event.pull_request.number }}.\n PR list is $ALL_PR.\n CI url: ${{ env.CURRENT_ACTION_URL }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.CI_PAT_ROBOT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_NAME/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"$COMMENT_BODY\"}"
        done
  
